Fix crash on html-mail entries with no URL
Before the regression, a URL of "None" was inserted in the href attribute, but
with 4cdf574 (Perform HTML escaping on text to be appended to HTML, 2021-03-19)
applied, calling saxutils.escape on None had crashed r2e with:

    Traceback (most recent call last):
      File "/rss2email/test/test.py", line 62, in fn
        self.run_single_test(config_path=test_path)
      File "/rss2email/test/test.py", line 135, in run_single_test
        feed.run()
      File "/rss2email/rss2email/feed.py", line 933, in run
        for (guid, state, sender, message) in self._process(parsed):
      File "/rss2email/rss2email/feed.py", line 394, in _process
        processed = self._process_entry(parsed=parsed, entry=entry)
      File "/rss2email/rss2email/feed.py", line 544, in _process_entry
        content = self._process_entry_content(
      File "/rss2email/rss2email/feed.py", line 821, in _process_entry_content
        _saxutils.escape(link), _saxutils.escape(subject)),
      File "/lib/python3.9/xml/sax/saxutils.py", line 27, in escape
        data = data.replace("&", "&amp;")
    AttributeError: 'NoneType' object has no attribute 'replace'