error: Don't explicitly store server in SMTPAuthenticationError
It's already being stored by SMTPConnectionError, which is called via
super().

Signed-off-by: W. Trevor King <wking@tremily.us>