error: Import __*__ metadata (URL, author, email)
These are used to format some of the log messages.

Signed-off-by: W. Trevor King <wking@tremily.us>